version: "3.8"

services:
  ml-model:
    build: ./model
    ports:
      - 8000:8000
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    volumes:
      - ./model:/app
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

    networks:
      - monitoring
    restart: unless-stopped
    

  # grafana:

  # node-exporter:

  # loki:

  # alloy:

  # alertmanager:

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
